# Curriculum Vitae {.unnumbered}

## Joan Q. Public

Department of Political Science  
University of Nevada, Las Vegas  
4505 S. Maryland Parkway  
Las Vegas, NV 89154  
Email: public@unlv.edu

## Education

### Ph.D. in Political Science
University of Nevada, Las Vegas (Expected 2024)  
Dissertation: "Dissertation Title"  
Committee: Available Upon Request

### M.A. in Political Science
University of Nevada, Las Vegas (2022)

### B.A. in Political Science
University of Nevada, Las Vegas (2020)  
*Magna Cum Laude*

## Research Interests

- American Politics
- Political Behavior
- Public Opinion
- Political Psychology

## Publications

### Working Papers
- "Working Paper Title 1" (Under Review)
- "Working Paper Title 2" (In Progress)

## Teaching Experience

### Instructor of Record
- Introduction to American Politics (Fall 2023)
- Research Methods in Political Science (Spring 2023)

### Teaching Assistant
- Political Theory (Fall 2022)
- Comparative Politics (Spring 2022)

## Research Experience

### Research Assistantships
- Graduate Research Assistant, Department of Political Science, UNLV (2022-Present)
- Research Assistant, Political Science Lab, UNLV (2021-2022)

## Conference Presentations
- "Presentation Title 1," Western Political Science Association (2023)
- "Presentation Title 2," American Political Science Association (2022)

## Awards and Honors
- Graduate College Research Award, UNLV (2023)
- Outstanding Graduate Student Award, Department of Political Science (2022)
- Dean's List, UNLV (2018-2020)

## Professional Service

### Departmental Service
- Graduate Student Representative, Department Committee (2022-2023)
- Peer Mentor, Political Science Graduate Program (2021-2022)

### Professional Memberships
- American Political Science Association
- Western Political Science Association
- Midwest Political Science Association

## Skills

### Technical Skills
- Statistical Software: R, Stata, SPSS
- Survey Design and Analysis
- Experimental Research Methods
- Qualitative Analysis Software

### Language Skills
- English (Native)
- Spanish (Professional Working Proficiency)

## References
Available Upon Request
